name: Deploy to Appspot (one-off)

on:
  workflow_dispatch:
    # Allows for manual triggering, to correct deployment issues.
    inputs:
      ref:
        description: "A tag name or SHA1 to deploy."
        required: true
      subdomain:
        description: "An appspot subdomain to deploy to.  Be careful!  Do not overwrite an existing subdomain!"
        required: true

jobs:
  appspot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: zulu
          java-version: 21

      - uses: ./.github/workflows/custom-actions/prep-for-appspot

      - uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: '${{ secrets.APPENGINE_DEPLOY_KEY }}'

      - uses: google-github-actions/deploy-appengine@a343979004148afb93c94c712b467e8e9f01b06b # v2
        with:
          project_id: shaka-player-demo
          version: ${{ inputs.subdomain }}
          promote: false
